<a href="https://colab.research.google.com/github/StephanyLera/Linear-Algebra_2nd-Sem/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Linear Algebra for ChE

## Laboratory 6 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

##Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using np.transpose() or using the T method

In [2]:
A = np.array([
              [1,2,5],
              [5,-1,0],
              [0,-3,3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [6]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [7]:
np.array_equiv(AT1, AT2)

True

In [8]:
B = np.array([
    [2,4,6,8],
    [1,2,3,4],
])
B.shape

(2, 4)

In [9]:
np.transpose(B).shape

(4, 2)

In [10]:
B.T.shape

(4, 2)

####Try to create your own matrix (you can try non-squares) to test transposition.

In [13]:
D=np.array([
    [2,4,6,8],
    [1,2,3,4]        
])
D.shape

(2, 4)

In [14]:
np.transpose(D).shape

(4, 2)

In [15]:
D.T.shape

(4, 2)

In [16]:
DT = D.T
DT

array([[2, 1],
       [4, 2],
       [6, 3],
       [8, 4]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [17]:
X = np.array([
    [5,8],
    [1,2]
])
Y = np.array([
    [-1,6],
    [5,9]
])

In [18]:
np.array_equiv(X, Y)

False

In [19]:
np.dot(X,Y)

array([[ 35, 102],
       [  9,  24]])

In [20]:
X.dot(Y)

array([[ 35, 102],
       [  9,  24]])

In [21]:
X @ Y

array([[ 35, 102],
       [  9,  24]])

In [22]:
np.matmul(X,Y)

array([[ 35, 102],
       [  9,  24]])

In [23]:
K = np.array([
    [5,7,9],
    [1,2,3],
    [4,8,12]
])
J = np.array([
    [-2,0,5],
    [2,-4,6],
    [7,4,-3]
])

In [24]:
np.array_equiv(K, J)

False

In [25]:
K @ J

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [26]:
K.dot(J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [27]:
np.matmul(K, J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In [28]:
np.dot(K, J)

array([[67,  8, 40],
       [23,  4,  8],
       [92, 16, 32]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$Z = \begin{bmatrix}2&4&5&5\\5&-2&6&6\\0&1&2&2\end{bmatrix}, O = \begin{bmatrix}1&1\\3&3\\-1&4\end{bmatrix}, E = \begin{bmatrix}0&1&1&3\\1&1&2&5\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [29]:
Z = np.array([
    [2, 4, 5],
    [5, -2, 6],
    [0, 1, 2]
])
O = np.array([
    [1,1],
    [3,3],
    [-1,4]
])
E = np.array([
    [0,1,1,3],
    [1,1,2,5]
])
print(Z.shape)
print(O.shape)
print(E.shape)

(3, 3)
(3, 2)
(2, 4)


In [30]:
O @ E

array([[ 1,  2,  3,  8],
       [ 3,  6,  9, 24],
       [ 4,  3,  7, 17]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [31]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [32]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [33]:
X @ Y.T

array([[13]])

And youcan see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

I'll be doing just one of the properties and I'll leave the rest to test your skills!

In [34]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,1]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
A.dot(np.eye(3))

array([[3., 2., 1.],
       [4., 5., 1.],
       [1., 1., 1.]])

In [38]:
np.array_equal(A@B, B@A)

False

In [39]:
E = A + (B + C)
E

array([[ 8,  4,  7],
       [ 8,  7, 11],
       [ 3,  5, 10]])

In [40]:
E = A @ (B @ C)
E

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [41]:
E = (B + C) @ A
E

array([[29, 26, 13],
       [30, 28, 16],
       [31, 33, 15]])

In [42]:
F = (A @ B) @ C
F

array([[ 65,  30,  53],
       [114,  50,  90],
       [ 32,  15,  29]])

In [43]:
np.array_equal(E, X)

False

In [44]:
np.array_equal(E, F)

False

In [45]:
A @ E

array([[178, 167,  86],
       [297, 277, 147],
       [ 90,  87,  44]])

In [46]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.array_equal(a_dot_z,z_mat)

True

In [49]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [50]:
A = np.array([
    [2,3],
    [1,6]
])
np.linalg.det(A)

9.000000000000002

In [51]:
B = np.array([
              [2, -3, 4],
              [1, 6 ,0],
              [-3, 6, 9]
])
np.linalg.det(B)

230.99999999999994

### Now other mathematics classes would require you to solve this by hand, and that is great for practicing your memorization and coordination skills but in this class we aim for simplicity and speed so we'll use programming but it's completely fine if you want to try to solve this one by hand.

In [52]:
B = np.array([
    [2,-3,4,6],
    [1,6,0,3],
    [-3,6,9,2],
    [1,2,3,4]
])
np.linalg.det(B)

-88.00000000000003

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [53]:
M = np.array([
    [3,6],
    [-4, 8]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [54]:
P = np.array([
              [3, 6, 9],
              [-4, 8, 12],
              [3, 6, 7]
])
Q = np.linalg.inv(P)
Q

array([[ 0.16666667, -0.125     , -0.        ],
       [-0.66666667,  0.0625    ,  0.75      ],
       [ 0.5       , -0.        , -0.5       ]])

In [55]:
P @ Q

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00],
       [4.4408921e-16, 0.0000000e+00, 1.0000000e+00]])

## And now let's test your skills in solving a matrix with high dimensions:

In [56]:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [57]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
weights = np.array([
    [0.2, 0.2, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.7 ],
       [0.82],
       [0.72]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

### Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
I = np.array([
    [2, 5, 7, 7],
    [13, 5, 12, 5],
    [3, 5, 21, 15],
    [4, 7, 93, 7]
])
L = np.array([
    [23, 5, 6, 3],
    [6, 4, 2, 8],
    [6, 8, 1, 9],
    [17, 7, 12,  8]
])
Y = np.array([
    [12, 2, 5, 6],
    [4, 66, 71, 3],
    [4, 6, 82, 3],
    [17, 67, 22, 19]
])


In [2]:
A = I.dot(L)
B = L.dot(Y)
C = Y.dot(I)
D = I.dot(A)
F = C.dot(Y)
G = I + L
H = Y + L
I = F + A

In [3]:
print('Property 1')
{np.array_equiv(I, L)}
print('AB=BA')
print('Matrix AB:')
print(np.matmul(A,B))
print('Matrix BA:')
print(np.matmul(B,A))
print('Approved!')

Property 1
AB=BA
Matrix AB:
[[ 217380  568518  718570  159603]
 [ 366610  910350 1176786  263341]
 [ 458233 1206385 1519570  337812]
 [ 951884 2498106 3246554  707335]]
Matrix BA:
[[1064193  690865  424435  787498]
 [ 936434  583982  352112  657426]
 [1231485  750637  464705  843086]
 [1723517 1092711  689431 1241755]]
Approved!


In [4]:
print('Property 2')
{np.array_equiv(I.dot(L), L.dot(Y))}
print('A(BC) = (AB)C')
print('Matrix A(BC):')
print(np.matmul(I, L))
print('Matrix A(BC):')
print(np.matmul(L, Y))
print('Approved!')

Property 2
A(BC) = (AB)C
Matrix A(BC):
[[ 959998  832308  274713 1013313]
 [4716105 3626929 1464737 4520023]
 [3672396 2860862 1146884 3590907]
 [4380269 3631361 1283925 4418361]]
Matrix A(BC):
[[ 371  613 1028  228]
 [ 232  824  654  206]
 [ 261 1149  878  234]
 [ 416 1104 1742  311]]
Approved!


In [5]:
print('Property 3')
{np.array_equiv(C.dot(Y), D)}
print('Matrix A(B+C)')
print(np.matmul(C, Y))
print('Matrix (AB) + (AC):')
print(np.add(Y, D))
print('Approved!')

Property 3
Matrix A(B+C)
[[  8287  27983  78036   7267]
 [ 50904 162386 301149  43930]
 [ 36709 132743 236951  34681]
 [ 43413 126203 330946  35150]]
Matrix (AB) + (AC):
[[11953  9395  4139 10704]
 [15330 10802  6163 12384]
 [25390 20574  9255 23566]
 [54684 36650 24396 42289]]
Approved!


In [6]:
print('Property 4')
{np.array_equiv(I.dot(A), I)}
print('(B+C)A = (BA) + (CA)')
print('Matrix (B+C)A:')
print(np.matmul(I, A))
print('Matrix (BA) + (CA):')
print(np.add(I, I))
print('Approved!')

Property 4
(B+C)A = (BA) + (CA)
Matrix (B+C)A:
[[ 59224408  37544432  24956093  42908740]
 [271643649 171998891 110316906 195693503]
 [215739608 136278770  87338122 154921681]
 [260467773 165778683 108924086 189394257]]
Matrix (BA) + (CA):
[[ 17048  56236 156298  14864]
 [102780 325204 602618  88314]
 [ 74378 266102 474360  70078]
 [ 88448 254088 662322  72222]]
Approved!


In [7]:
print('Property 5')
{np.array_equiv(Y.dot(1), D)}
print('A(1)=A')
print('Matrix A(1):')
print(np.multiply(Y, 1))
print('Matrix A:')
print(D)
print('Approved!')

Property 5
A(1)=A
Matrix A(1):
[[12  2  5  6]
 [ 4 66 71  3]
 [ 4  6 82  3]
 [17 67 22 19]]
Matrix A:
[[11941  9393  4134 10698]
 [15326 10736  6092 12381]
 [25386 20568  9173 23563]
 [54667 36583 24374 42270]]
Approved!


In [8]:
print('Property 6')
{np.array_equiv(L.dot(0), 0)}
print('A(0)=0')
print('Matrix A(0):')
print(np.multiply(A, 0))
print('Approved!')

Property 6
A(0)=0
Matrix A(0):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Approved!
